-- 코드를 입력하세요
SELECT date_format(A.SALES_DATE, '%Y-%m-%d') as SALES_DATE, 
    A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
FROM (
    select SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
    from ONLINE_SALE
    UNION ALL
    select SALES_DATE,PRODUCT_ID,NULL as USER_ID,SALES_AMOUNT
    from OFFLINE_SALE )  as A
    
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID