SELECT month(START_DATE) as MONTH,
        CAR_ID, count(HISTORY_ID) as RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID in (
    select CAR_ID 
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    where date_format(START_DATE,'%Y-%m') BETWEEN '2022-08' and '2022-10'
    group by CAR_ID 
    having COUNT(HISTORY_ID) >= 5
)
and date_format(START_DATE,'%Y-%m') BETWEEN '2022-08' and '2022-10'
GROUP BY MONTH, CAR_ID	
ORDER BY MONTH, CAR_ID desc 