-- 2022년 1월의 카테고리 별 도서 판매량을 합산
-- 카테고리명을 기준으로 오름차순 
SELECT CATEGORY, 
    sum(SALES) as TOTAL_SALES
FROM BOOK b
LEFT JOIN BOOK_SALES s ON b.BOOK_ID= s.BOOK_ID 
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY 