-- 2022년 1월 판매 기준, 카테고리 별 매출액
-- 저자 ID를 오름차순, 카테고리 내림차순 
SELECT b.AUTHOR_ID,AUTHOR_NAME,CATEGORY,
        sum(SALES*PRICE) as TOTAL_SALES
FROM BOOK b
LEFT JOIN AUTHOR a ON b.AUTHOR_ID=a.AUTHOR_ID
LEFT JOIN BOOK_SALES  s ON b.BOOK_ID=s.BOOK_ID 
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY b.AUTHOR_ID,CATEGORY
ORDER BY b.AUTHOR_ID, CATEGORY desc