-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, (sum(off.SALES_AMOUNT)*p.PRICE) as SALES 
FROM PRODUCT p
JOIN OFFLINE_SALE off ON p.PRODUCT_ID = off.PRODUCT_ID 
GROUP BY p.PRODUCT_CODE 
ORDER BY SALES desc, p.PRODUCT_CODE 
